plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.jancoo.contractchecker.localocr'
version = '0.1.0'

repositories {
  maven { url 'https://jitpack.io' }
}

android {
  namespace "com.jancoo.contractchecker.localocr"

  defaultConfig {
    minSdkVersion 23
    versionCode 1
    versionName "0.1.0"
  }

  sourceSets {
    main {
      assets.srcDirs += ["../../../assets"]
    }
  }
}

dependencies {
  implementation 'cz.adaptech.tesseract4android:tesseract4android:4.9.0'
}
