"""Public Streamlit demo for deterministic contract checks."""

from __future__ import annotations

from dataclasses import asdict
from typing import Any

from contract_checker.ocr_image import ocr_image_to_text
from contract_checker.pipeline import analyze_contract_text
from contract_checker.report import result_to_markdown
from contract_checker.web_helpers import result_summary, sample_contract_text, status_badge


def _result_payload(result: Any) -> dict[str, Any]:
    """Build the raw JSON payload shown in the public demo."""

    return asdict(result)


def _render_analysis(result: Any) -> None:
    """Render deterministic analysis sections for pasted or OCR text."""

    import streamlit as st

    summary = result_summary(result)

    st.subheader("Russian summary / Сводка на русском")
    russian_labels = {
        "Risk level": "Уровень риска",
        "Word count": "Количество слов",
        "Missing checks": "Отсутствующие проверки",
        "Cautions": "Предупреждения",
    }
    cols = st.columns(4)
    for column, (label, value) in zip(cols, summary.items(), strict=True):
        column.metric(russian_labels.get(label, label), value)

    st.subheader("Fields / Поля")
    fields = [
        {
            "field": finding.title,
            "status": finding.status,
            "detail": finding.detail,
        }
        for finding in result.findings
    ]
    st.dataframe(fields, use_container_width=True, hide_index=True)

    st.subheader("Validations / Проверки")
    for finding in result.findings:
        with st.expander(f"{status_badge(finding.status)} — {finding.title}", expanded=True):
            st.write(finding.detail)
            st.write(f"**Recommendation:** {finding.recommendation}")

    st.subheader("Crop requests / Запросы фрагментов")
    crop_requests = [
        {
            "topic": finding.title,
            "request": "Please manually review the relevant document area; handwritten Hebrew is not verified.",
        }
        for finding in result.findings
        if finding.status in {"Missing", "Caution"}
    ]
    if crop_requests:
        st.dataframe(crop_requests, use_container_width=True, hide_index=True)
    else:
        st.success("No additional crop requests were generated by the deterministic demo checks.")

    st.subheader("Raw JSON")
    st.json(_result_payload(result))

    st.subheader("Export")
    report_markdown = result_to_markdown(result)
    st.download_button(
        "Download Markdown report",
        data=report_markdown,
        file_name="contract-check-report.md",
        mime="text/markdown",
    )
    st.markdown(report_markdown)


def _render_paste_tab() -> None:
    """Render the pasted-text workflow."""

    import streamlit as st

    if "contract_text" not in st.session_state:
        st.session_state.contract_text = ""

    if st.button("Load synthetic sample contract"):
        st.session_state.contract_text = sample_contract_text()

    contract_text = st.text_area(
        "Contract text",
        key="contract_text",
        height=280,
        placeholder="Paste public-safe contract text here...",
    )

    if not contract_text.strip():
        st.warning("Add contract text to run the demo checks.")
        return

    result = analyze_contract_text(contract_text)
    _render_analysis(result)


def _render_image_tab() -> None:
    """Render the experimental server-side OCR upload workflow."""

    import streamlit as st

    st.warning(
        "OCR is experimental. Printed Hebrew may work; handwritten Hebrew is not trusted automatically."
    )
    uploaded_image = st.file_uploader(
        "Upload a public-safe printed contract image",
        type=["jpg", "jpeg", "png"],
        accept_multiple_files=False,
    )

    if uploaded_image is None:
        st.info("Upload a JPG or PNG image to try server-side Tesseract OCR.")
        return

    st.image(uploaded_image, caption="Uploaded image preview", use_container_width=True)

    if "last_ocr_file" not in st.session_state or st.session_state.last_ocr_file != uploaded_image.name:
        st.session_state.last_ocr_file = uploaded_image.name
        st.session_state.ocr_text = ""
        st.session_state.ocr_result = None

    if st.session_state.ocr_result is None:
        with st.spinner("Running OCR with server-side Tesseract..."):
            uploaded_image.seek(0)
            st.session_state.ocr_result = ocr_image_to_text(uploaded_image)
            st.session_state.ocr_text = st.session_state.ocr_result["raw_text"]

    ocr_result = st.session_state.ocr_result
    if not ocr_result["ocr_available"]:
        st.error("Image OCR is unavailable in this deployment. Please use Paste Hebrew text for now.")
        if ocr_result["error"]:
            st.caption(ocr_result["error"])
        return

    if ocr_result["blocks"]:
        with st.expander("OCR block diagnostics", expanded=False):
            st.dataframe(ocr_result["blocks"], use_container_width=True, hide_index=True)

    edited_ocr_text = st.text_area(
        "Extracted OCR text (editable before analysis)",
        key="ocr_text",
        height=280,
        help="Review and correct OCR text before running the deterministic checks.",
    )

    if st.button("Analyze OCR text"):
        if not edited_ocr_text.strip():
            st.warning("OCR text is empty. Paste or type text before analysis.")
            return
        result = analyze_contract_text(edited_ocr_text)
        _render_analysis(result)


def main() -> None:
    """Run the Streamlit application."""

    import streamlit as st

    st.set_page_config(page_title="Contract Checker Demo", page_icon="📄", layout="wide")
    st.title("📄 Contract Checker Demo")
    st.caption(
        "A public-safe demo that uses deterministic checks only. It does not use LLMs, "
        "paid APIs, secrets, or real contract photos."
    )

    st.info(
        "This prototype does not replace a lawyer. OCR mistakes are possible. "
        "Handwritten Hebrew is not treated as verified fact."
    )

    paste_tab, image_tab = st.tabs(["Paste Hebrew text", "Upload image"])
    with paste_tab:
        _render_paste_tab()
    with image_tab:
        _render_image_tab()


if __name__ == "__main__":
    main()
