plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.tesseractocr'
version = '0.1.0'

android {
  namespace "expo.modules.tesseractocr"

  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
}

repositories {
  maven { url "https://jitpack.io" }
}

dependencies {
  implementation 'cz.adaptech.tesseract4android:tesseract4android-openmp:4.9.0'
}
